### ISSUE TITLE
Enter doesn't send form

### ISSUE THREAD

**Issue by johnrackles** [CEREBR4L/linkr#13]
It's a bit irritating that you can't get a new link by using the enter key and only by clicking the button. The fix should be relatively easy, but I don't know any Angular so I can't make a PR.

I'd change the

`<div class="form">
...
</div>`

to a real html

`<form></form>`

Element. Then you can use 

> ng-submit

on the form instead of 

> ng-click

on the button element and it should work with the button and the enter key.

**Comment by CEREBR4L** [comment]
@johnrackles I will look to implement something for this soon, thanks for raising :)

**Comment by CEREBR4L** [comment]
@johnrackles I have a fix for this that will be push today :+1:
